In [9]:
import numpy as np
from random import randint
#import framework
#import implementations as func
import matplotlib.pyplot as plt
import importlib
import pandas as pd
import scipy.signal as scp
import tensorflow as tf
import target_data_gen
from target_data_gen import get_sizes
from target_data_gen import target_gen
%load_ext autoreload
%autoreload 2
%matplotlib notebook

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
class Linear():  
  
    # initialization function
    def __init__(self, inputs, outputs):
        print("creating Linear layer")
        lim = np.sqrt(6/(inputs+outputs))
        self.W = np.random.uniform(-lim,lim,(inputs+1, outputs))
        self.W[0,:].fill(0)
        self.dW = np.zeros((inputs+1, outputs))
        self.Linear_updateW = Optimizer(self.W)
    # forward pass calculation
    # receives input tensor of shape : [nb_samples x insize]
    def forward(self,X): 
        # [nb_samples x insize] x [insize x outsize] + [nb_samples x outsize] => [nb_samples x outsize]
        H = X @ self.W
        return H
    
    # backward pass calculation
    # receives gradient of the next layer
    # returns gradient with respect to the input. 
    # returns derivative with respect to the weights.
    def backward(self,dH, X):
        # matrix multiplication [nb_samples, outsize]*[insize, outsize]^t => [nb_samples x insize]
        # sum over samples for parameters (normal Gradient Descent. If divided into batches -> SGD)
        dX = dH @ np.transpose(self.W)
        #print(dH, self.dW)
        self.dW = np.transpose(X) @ dH
        self.W = self.Linear_updateW.adam_update(self.W, self.dW)
        return dX, self.dW
    
  

In [11]:
def orthogonal_initializer(shape):
    num_rows = 1
    for dim in shape[:-1]:
        num_rows *= dim
    num_cols = shape[-1]
    flat_shape = (num_rows, num_cols)
    a = np.random.normal(0.0, 1.0, flat_shape)
    u, _, v = np.linalg.svd(a, full_matrices=False)
    # Pick the one with the correct shape.
    q = u if u.shape == flat_shape else v
    q = q.reshape(shape)
    return q[:shape[0], :shape[1]]

In [12]:
class GRU():
    #Wz, Wr, Wh, Uz, Ur, Uh = np.array()
    #z, r, h, s = np.array()
    
    def __init__(self,sequences, timesteps, inputs, outputs):
        print("creating GRU layer")
        lim_w = np.sqrt(6/(inputs+outputs))
        lim_u = np.sqrt(6/(2*outputs))
        lim_wlin = np.sqrt(6/(outputs))
        self.Wz = np.random.uniform(-lim_w,lim_w,(inputs, outputs))
        self.Wr = np.random.uniform(-lim_w,lim_w,(inputs, outputs))
        self.Wh = np.random.uniform(-lim_w,lim_w,(inputs, outputs))
        self.Bz = np.zeros((1, outputs))
        self.Br = np.zeros((1, outputs))
        self.Bh = np.zeros((1, outputs))
        self.Wlin = np.random.uniform(-lim_wlin, lim_wlin, (outputs, 1))
        self.Blin = np.zeros((1,1))
        print(self.Wz.shape)
        self.y, self.dy = np.zeros((sequences, 1)) ,np.zeros((sequences,1))
        #self.Uz, self.Ur, self.Uh = np.random.uniform(-lim_u,lim_u,(outputs, outputs)), np.random.uniform(-lim_u,lim_u,(outputs, outputs)), np.random.uniform(-lim_u,lim_u,(outputs, outputs))
        self.Uz = orthogonal_initializer((outputs, outputs))
        self.Ur = orthogonal_initializer((outputs, outputs))
        self.Uh = orthogonal_initializer((outputs, outputs))
        self.z, self.r = np.zeros((sequences,timesteps,outputs)),np.zeros((sequences,timesteps,outputs))
        self.h, self.s = np.zeros((sequences,timesteps,outputs)),np.zeros((sequences,timesteps,outputs))
        print(self.s.shape)
        self.dWlin = np.zeros((outputs,1))
        self.GRU_updateBz = Optimizer(self.Bz)
        self.GRU_updateBr = Optimizer(self.Br)
        self.GRU_updateBh = Optimizer(self.Bh)
        self.GRU_updateWz = Optimizer(self.Wz)
        self.GRU_updateWr = Optimizer(self.Wr)
        self.GRU_updateWh = Optimizer(self.Wh)
        self.GRU_updateUz = Optimizer(self.Uz)
        self.GRU_updateUr = Optimizer(self.Ur)
        self.GRU_updateUh = Optimizer(self.Uh)
        self.Lin_updateW = Optimizer(self.Wlin)
        self.Lin_updateB = Optimizer(self.Blin)
        #self.s_aug = np.zeros((sequences, timesteps, outputs+1))
        #self.s_aug[:,:,0].fill(1) # bias
    def forward(self,X):
        # initialize
        # first iteration
        #print(self.z.shape, X.shape)
        outputs = self.s.shape[2]
        
        self.z[:,0,:] = sigmoid(X[:,0,:] @ self.Wz + self.Bz) #[seq * time * OUT] = [seq * time * IN] @ [IN * OUT]
        self.r[:,0,:] = sigmoid(X[:,0,:] @ self.Wr + self.Br)
        self.h[:,0,:] = tanh(X[:,0,:] @ self.Wh + self.Bh)
        self.s[:,0,:] = (1-self.z[:,0,:])*self.h[:,0,:]
        for t in range(1, X.shape[1]):
            self.z[:,t,:] = sigmoid(X[:,t,:] @ self.Wz + self.s[:,t-1,:] @ self.Uz + self.Bz) #[samples,outputs]+[1, outputs]
            self.r[:,t,:] = sigmoid(X[:,t,:] @ self.Wr + self.s[:,t-1,:] @ self.Ur + self.Br)
            self.h[:,t,:] = tanh(X[:,t,:] @ self.Wh + (self.r[:,t,:] *self.s[:,t-1,:]) @ self.Uh + self.Bh)
            self.s[:,t,:] = self.z[:,t,:]*self.s[:,t-1,:] + (1-self.z[:,t,:])*self.h[:,t,:]
            #self.s_aug [:,t,1:outputs+1] = self.s[:,t,:]
        self.y = sigmoid(self.s[:,self.s.shape[1]-1,:] @ self.Wlin + self.Blin)
        return self.y
    
    def backward(self,dy, X):
        inputs = X.shape[2]
        outputs = self.s.shape[2]
        dsnext = np.zeros_like(self.s[:,0,:])
        dsnext = dy @ np.transpose(self.Wlin)
        dX = np.zeros((X.shape))
        dWlin = np.transpose(self.s[:,self.s.shape[1]-1,:])@dy
        dBlin = np.sum(dy, axis = 0).reshape(1,-1)
        dWz, dWr, dWh = np.zeros((inputs, outputs)), np.zeros((inputs, outputs)), np.zeros((inputs, outputs))
        dUz, dUr, dUh = np.zeros((outputs, outputs)), np.zeros((outputs, outputs)), np.zeros((outputs, outputs))
        dBz, dBr, dBh = np.zeros((1, outputs)), np.zeros((1, outputs)), np.zeros((1, outputs))
        for t in reversed(range(X.shape[1])):
            #print(ds.shape, self.z.shape)
            
            
            ds = dsnext
            dh = ds*(1-self.z[:,t,:])
            dh_l = dh*tanh(self.h[:,t,:], deriv=True)
            #print("GRU backward", dh_l.shape)
            dWh += np.transpose(X[:,t,:]) @ dh_l # [1 x IN].T @ [1 x OUT]
           
            #print(self.dWh.shape)
            dUh += np.transpose(self.r[:,t,:]*self.s[:,t-1,:]) @ dh_l # [1 x OUT].T @ ([1 x OUT] * [1 x OUT])
            dBh += np.sum(dh_l, axis = 0).reshape(1,-1)
            #drsp = dh_l @ np.transpose(Uh)
            
            drsp = dh_l @ np.transpose(self.Uh)# [1 x OUT] @ [OUTin x OUT].T
           # dr = dh_l * (self.s[:,t-1,:] @ self.Uh) #[1 x OUT] = [ 1 x OUT]*([1 x OUTin] @ [OUTin x OUT])
            dr = drsp * self.s[:,t-1,:]
            dr_l = dr * sigmoid(self.r[:,t,:], deriv=True) # replace by sigmoid
            
            dWr += np.transpose(X[:,t,:]) @ dr_l # [ IN x OUT] = [1 x IN].T @ [1 x OUT]
            dUr += np.transpose(self.s[:,t-1,:]) @ dr_l # [OUTin x OUT ] = [ 1 x OUTin].T @ [ 1 x OUT]
            dBr += np.sum(dr_l, axis = 0).reshape(1,-1)
            
            dz = (self.s[:,t-1,:]-self.h[:,t,:]) * dh  # [1 x OUT] = ( [1 x OUT] - [1 x OUTin] ) * [1 x OUT]
            dz_l = dz * sigmoid(self.z[:,t,:], deriv=True)
            
            dWz += np.transpose(X[:,t,:]) @ dz_l
            dUz += np.transpose(self.s[:,t-1,:]) @ dz_l
            dBz += np.sum(dz_l, axis = 0).reshape(1,-1)
            
            # calculate gradient w.r.t s[t-1]
            ds_fz_inner = dz_l @ np.transpose(self.Uh) #  [1 x OUTin] =  [1 x OUT] @ [OUTin x OUT].T
            ds_fz = ds * (1-self.z[:,t,:]) # [1 x OUTin] = [1 x OUT] * [1 x OUT]
            ds_fh = drsp * self.r[:,t,:] # [1 x OUTin] = [1 x OUT] * [1 x OUT]
            ds_fr = dr_l @ np.transpose(self.Ur)
            
            dsnext = ds_fz_inner + ds_fz + ds_fh + ds_fr
            for n in range(0, t+1):
                dX[:,n,:]+=dh_l @ np.transpose(self.Wh) + dr_l @ np.transpose(self.Wr) + dz_l @ np.transpose(self.Wz)
            
            #update weights
        self.Wz = self.GRU_updateWz.adam_update(self.Wz, dWz)
        self.Wr = self.GRU_updateWr.adam_update(self.Wr, dWr)
        self.Wh = self.GRU_updateWh.adam_update(self.Wh, dWh)
        self.Uz = self.GRU_updateUz.adam_update(self.Uz, dUz)
        self.Ur = self.GRU_updateUr.adam_update(self.Ur, dUr)
        self.Uh = self.GRU_updateUh.adam_update(self.Uh, dUh) 
        self.Bz = self.GRU_updateBz.adam_update(self.Bz, dBz)
        self.Br = self.GRU_updateBr.adam_update(self.Br, dBr)
        self.Bh = self.GRU_updateBh.adam_update(self.Bh, dBh)
        self.Wlin = self.Lin_updateW.adam_update(self.Wlin, dWlin)
        self.Blin = self.Lin_updateB.adam_update(self.Blin, dBlin)
        return ds, dX
    
    def change_input_size(self, sequences, timesteps,outputs):
        self.z, self.r = np.zeros((sequences,timesteps,outputs)),np.zeros((sequences,timesteps,outputs))
        self.h, self.s = np.zeros((sequences,timesteps,outputs)),np.zeros((sequences,timesteps,outputs))
        self.s_aug = np.zeros((sequences, timesteps, outputs+1))
        self.y = np.zeros((sequences, timesteps, 1))
    def get_parameters(self):
        return self.Wz, self.dWz,self.Wr, self.dWr,self.Wh, self.dWh,self.Uz, self.dUz,self.Ur, self.dUr,self.Uh, self.dUh

In [5]:
A = np.array ([[1,2],[3,4],[5,6]])
B = np.array([[1,2]])
A+B


array([[2, 4],
       [4, 6],
       [6, 8]])

In [5]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A)
C = np.sum(A,axis=0)
print(C)
print(B)
print(C.reshape(1,-1)*B)

[[1 2]
 [3 4]]
[4 6]
[[1 2]
 [3 4]]
[[ 4 12]
 [12 24]]


In [239]:
X = np.array([np.arange(1,10), np.arange(1,10)])
X.reshape(1,2,9)
print(X)
GRU_layer_0 = GRU(sequences=1, timesteps=2, inputs=9, outputs=5)
s = GRU_layer_0.forward(X.reshape(1,2,9))

print(s)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
creating GRU layer
(9, 5)
(1, 2, 5) (1, 2, 9)
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [13]:
def sigmoid(input, deriv=False): #requires output of forward prop for derivativef
    if deriv:
        return input*(1-input)
    else:
        return 1 / (1 + np.exp(-input))

def hard_sigmoid(input, deriv = False): #requires input of forward prop for derivative.
    if deriv:
        temp = np.copy(input)
        temp[input <= -2] = 0
        temp[input > -2] = 0.25*input
        temp[input >= 2] = 0
        return temp
    else:
        return np.maximum(0, np.minimum(1, (input + 2) / 4))
def tanh(input, deriv=False): #requires output of forward prop for derivative
    if deriv:
        return 1 - input ** 2
    else:
        return np.tanh(input)

def reLU(input, deriv=False): #requires input of forward prop for derivative
    if deriv:
        output = np.copy(input)
        output[input > 0.0 ] = 1.0
        output[input <= 0.0] = 0.0
        return output
    else:
        output = np.copy(input)
        output[input < 0.0 ] = 0.0
        return output

In [5]:
#test
input_shape = (32,10,2)
X=np.zeros((input_shape))
print(X.shape)

(32, 10, 2)


In [14]:
class Conv2D():
    height = 0
    width = 0
    nb_seq = 0
    timesteps = 0
    new_height = 0
    new_width = 0
    K = 0
    M = 0
    N = 0
    def __init__(self, kernel_height, kernel_width, filters):
        self.W = np.random.uniform(-1,1,(kernel_height, kernel_width, filters))
        self.B = np.zeros((1, filters))
        self.dW = np.zeros((kernel_height, kernel_width, filters))
        self.dB = np.zeros((1, filters))
        print('Creating Conv2D layer')
        self.Conv2D_updateW = Optimizer(self.W)
        self.Conv2D_updateB = Optimizer(self.B)
    # W.shape : [kernel_height, kernel_width, nb_filters]
    # X.shape : [samples, timesteps, height, width, 1]
    # B.shape : [1, nb_filters]
    def forward(self, X):
        #print("conv2d Xshape", X.shape)
        self.height = X.shape[2]
        self.width = X.shape[3]
        self.M = self.W.shape[0]
        self.N = self.W.shape[1]
        self.K = self.W.shape[2]
        self.nb_seq = X.shape[0]
        self.timesteps = X.shape[1]
        #print(self.timesteps)
        #compute new dimensions
        self.new_height = self.height - self.M + 1
        self.new_width = self.width - self.N + 1
        
       # print(new_height, new_width)
        h = np.zeros((self.nb_seq, self.timesteps, self.new_height, self.new_width, self.K))
        for k in range(self.K):
            for i in range(self.new_height):
                for j in range(self.new_width):
                    h[:,:,i,j,k]=np.sum(X[:,:,i:i+self.M, j:j+self.N,0]*self.W[:,:,k], axis =(2,3))+self.B[0,k]
        return h
    # dH has dimensions of H which means in case of X.shape=[3,3,1], W.shape=[2,2,1] => H.shape=[2,2,1]
    # dX should have the same shape as X, i.e dX.shape=[3,3,1] = dH conv2D flipped W 'FULL'
    def backward(self, dH, X):
        # dw is the same operation as in forward propagation. 
        # no need to compute dX in our case because the conv2D layer is the first layer and means the end of backprop. algorithm.
        for k in range(self.K):
            self.dB[:,k] = np.sum(dH[:,:,:,:,k])
            for i in range(self.M):
                for j in range(self.N):
                    #average over all the sequences and timesteps
                    self.dW[i,j,k]=np.sum(X[:,:,i:i+self.new_height, j:j+self.new_width,0]*dH[:,:,:,:,k])
        self.W = self.Conv2D_updateW.adam_update(self.W, self.dW)
        self.B = self.Conv2D_updateB.adam_update(self.B, self.dB)
        return 

In [6]:
#test for conv2d
X=np.array([[3.0,5,6], [1,2,4], [2,3,5]]).reshape(3,3,1)
W=np.array([[2,1.0],[1,4]]).reshape(-1,2,1)
#W = np.rot90(W,2)
print(W.shape)
B=np.array([0.5]).reshape(-1,1)
print(X.shape)
conv_layer1 = Conv2D()
H = conv_layer1.forward(X, W, B)
print(H, H.shape)
print(H[1,0,0])

# check against scp : kernel is flipped here.
X_scp = X.reshape(-1,3)
W_scp = W.reshape(-1,2)
H_scp = scp.convolve2d(X_scp, W_scp, mode = 'valid')
#print(H_scp)
#print(X[1,0,0])

#check against tensorflow

X_tf = X.reshape(1,3,3,1)
W_tf = W.reshape(2,2,1,1)
sess = tf.Session()
H_tf = sess.run(tf.nn.conv2d(X_tf, W_tf, strides = (1,1,1,1), padding = 'VALID'))
sess.run(tf.Print(H_tf, [H_tf]))


(2, 2, 1)
(3, 3, 1)


TypeError: __init__() missing 3 required positional arguments: 'kernel_height', 'kernel_width', and 'filters'

In [15]:
class MaxPool2D():
    height = 0
    width = 0
    M = 0
    N = 0
    K = 0
    nb_seq = 0
    timesteps = 0
    def __init__(self):
        print('creating 2D Max pooling layer')
    
    def forward(self, X, pool):
        self.height = X.shape[2]
        self.width = X.shape[3]
        self.M = pool[0]
        self.N = pool[1]
        self.K = X.shape[4]
        self.nb_seq = X.shape[0]
        self.nb_timesteps = X.shape[1]
        if self.height%2 == 1:
            X = np.delete(X, obj=self.height-1, axis=2)
            self.height = X.shape[2]
        if self.width%2 == 1:
            X = np.delete(X, obj=self.width-1, axis=3)
            self.width = X.shape[3]
        X_argmax = np.copy(X)
       
        #print(self.M, self.N)
        #compute new sizes
        new_height = int(self.height/self.M)
        new_width = int(self.width/self.N)
        H = np.zeros((self.nb_seq, self.nb_timesteps, new_height, new_width, self.K))
        #print(H.shape)
       
        #start pooling
        for k in range(self.K):
            for i in range(0,self.height,self.M):
                for j in range(0,self.width,self.N): #genericity loss here, only valid with kernel width = 2.
                    X_temp = X[:,:,i:i+self.M, j:j+self.N, k].reshape(self.nb_seq, self.nb_timesteps, self.M*self.N,1)
                    H[:,:,int(i/self.M), int(j/self.N), k] = np.amax(X[:,:,i:i+self.M, j:j+self.N, k], axis=(2,3)) 
                    X_argmax[:,:, i, j, k] = (np.argmax(X_temp, axis = 2)).reshape(self.nb_seq, self.nb_timesteps) 
                    X_argmax[:,:, i+self.M-1, j, k] = (np.argmax(X_temp, axis = 2)).reshape(self.nb_seq, self.nb_timesteps) 
                    X_argmax[:,:, i, j+self.N-1, k] = (np.argmax(X_temp, axis = 2)).reshape(self.nb_seq, self.nb_timesteps) 
                    X_argmax[:,:, i+self.M-1, j+self.N-1, k] = (np.argmax(X_temp, axis = 2)).reshape(self.nb_seq, self.nb_timesteps) 
        return H, X_argmax
        
    def backward(self, X_argmax, dH):
        dX = np.zeros((X_argmax.shape))
        for k in range(self.K):
            for i in range(0, self.height, self.M):
                for j in range(0,self.width, self.N):
                    dX[:,:, i:i+self.M,j:j+self.N,k] = self.norm_argmax(X_argmax[:,:,i:i+self.M, j:j+self.N, k], dH[:,:,int(i/self.M), int(j/self.N), k])       
        return dX
                                                                
    def norm_argmax(self, X, dH):
        #print("X_argmax shape maxpool = ", X.shape)
        h = X.shape[2]
        w = X.shape[3]
        I = np.array(np.arange(X.shape[2]+X.shape[3]))
        Ibig = np.zeros_like(X)
        #print("Maxpoolbackward:", X.shape, Ibig.shape, I.shape)
        Ibig = np.tile(I,(X.shape[0], X.shape[1],1))
        #print("ibig", Ibig.shape)
        Xresh = X.reshape(X.shape[0], X.shape[1], Ibig.shape[2]) # multidimensional
        diff = (Xresh-Ibig).astype(int)
        #duplicate dH x 4
        dH_dupl = np.zeros_like(X)
        for m in range(2):
            for n in range(2):
                dH_dupl[:,:,m,n] = dH
        # reshape to make boolean assignment
        Xresh = Xresh.flatten()
        diff = diff.flatten()
        dHflat = dH_dupl.flatten()
        #print("dH shape", dH.shape)
        Xresh[diff != 0] = -1
        #print("xresh shape", Xresh.shape, diff.shape)
        deriv = np.copy(Xresh)
        deriv[Xresh > -1.0] = dHflat[Xresh > -1.0]
        deriv[Xresh == -1.0] = 0.0
        deriv = deriv.reshape(X.shape[0],X.shape[1],h, w)
        #print("deriv shape max pool = ", deriv.shape)
        return deriv

In [328]:
# test 
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A, A.shape)
print(A[0,1,0])
B=np.array([[1,2],[3,4]])
print(B, B.shape)
print(B[1,0])
int(98/2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
3
[[1 2]
 [3 4]] (2, 2)
3


49

In [7]:
# test Max Pool 2D
X = np.zeros((1,1,4,4,1))
for i in range(X.shape[2]):
    for j in range(X.shape[3]):
        X[:,:,i,j,:]= i -2*j 
x_dummy=X.reshape(4,4)
ddH = np.ones((5,5,1))
maxPool2D_layer2 = MaxPool2D()
pool = np.array([2,2])
H, X_arg =maxPool2D_layer2.forward(X, pool)
dXmaxpool_test = max, X_arg[1Pool2D_layer2.backward(X_arg, ddH)
print(X_arg)

SyntaxError: invalid syntax (<ipython-input-7-caa07f00056f>, line 11)

In [7]:
print(H.reshape(5,5))

[[ 2.  4.  6.  8. 10.]
 [ 4.  6.  8. 10. 12.]
 [ 6.  8. 10. 12. 14.]
 [ 8. 10. 12. 14. 16.]
 [10. 12. 14. 16. 18.]]


In [8]:
print(X.reshape(10,10))

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]]


In [9]:
print(X_arg.reshape(10,10))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [16]:
#loss function
def CrossEntropy(yHat, y):
    length = yHat.shape[0]
    y = y.flatten()
    yHat = yHat.flatten()
    #print(yHat.shape)
    output = np.copy(y)
    #print(output.shape)
    output[y==1]= -np.log(yHat)[y==1]
    output[y==0] = -np.log(1 - yHat)[y==0] # weighting of the classes
    #output = -y*np.log(yHat+10**-8)+(1-y)*np.log(1-yhat+10**-8)
    output1 = np.sum(np.abs(output))/800
    return output1, output
def derivCrossEntropy(yHat, y):
    dloss = np.zeros((yHat.shape[0]))
    for i in range(yHat.shape[0]):
        if yHat[i] < 1 and yHat[i] > 0:
            dloss[i] = -y[i]/yHat[i] + (1-y[i])/(1-yHat[i])
        elif yHat[i] == 1 and y[i] == 1:
            dloss[i] = -1
        elif yHat[i] == 0 and y[i] == 0:
            dloss[i] = 1
        elif yHat[i] == 1 and y[i] == 0:
            dloss[i] = 2*63
        elif yHat[i] == 0 and y[i] == 1:
            dloss[i] = -2*63
    return dloss
    

In [9]:
# TB done:
# write main function calling forward & backward
# write flattening (can be done in MAIN)
# try it out!

In [17]:
#weight update
class Optimizer():
    # initialize training parameters
    def __init__(self, W):
       # self.Wconv = np.zeros((nb_Wconv1, nb_Wconv2))
       # self.Bconv = np.zeros((nb_Bconv))
       # self.Wr, self.Wh, self.Wz = np.zeros((nb_GRUin, nb_GRUout)), np.zeros((nb_GRUin, nb_GRUout)), np.zeros((nb_GRUin, nb_GRUout))
       # self.Ur, self.Uh, self.Uz = np.zeros((nb_GRUout, nb_GRUout)), np.zeros((nb_GRUout, nb_GRUout)), np.zeros((nb_GRUout, nb_GRUout))
       # self.Wlin = np.zeros((nb_Wlin)) # only 1 output
        self.alpha = 0.001
        self.beta1 = 0.9
        self.beta2 = 0.999
        self.eps = 10**-7
        self.v = np.zeros((W.shape))
        self.m = np.zeros((W.shape))
        self.n_iters = 1
    def adam_update(self, W, dW):
        #np.clip(dW, -5, 5, out=dW)
        self.m = self.beta1*self.m + (1 - self.beta1)*dW
        self.v = self.beta2*self.v + (1 - self.beta2)*np.power(dW, 2)
        m_corr = self.m/(1-self.beta1)
        v_corr = self.v/(1-self.beta2)
        #if self.n_iters % 10 == 0:
        #self.alpha = self.alpha/np.sqrt(0.1*self.n_iters+0.9)
        W = W  - self.alpha*m_corr/(np.sqrt(v_corr)+self.eps)   
        #W = W - self.alpha*dW
        self.n_iters += 1
        return W



In [18]:
#main

# get data
np.random.seed(0)
output = 1
#X=np.array(sigbufs
batch_size = 100 #(length)
batch_mod = 10000
dataset_size = 18
X, Y = list(), list()

#**********************CALLLING DATA GENERATOR FUNCTION ***********************
X, input_size, length = get_sizes(X, dataset_size)
print(X.shape)
#Defining sizes for input/target data
Y=np.zeros((dataset_size, batch_mod, output))
#yhat=np.zeros((dataset_size, batch_mod, output))


#***********************CALLING TARGET GENERATOR FUNCTION**********************
file = 'database/chb01-summary.txt'
Y = target_gen(output, batch_mod, dataset_size, batch_size, file)
#******************************************************************************
print(Y.shape)

input_size_new = 23
#elements of each frame
batch_size_new = 100
#time steps equivalent 
timesteps= 10 # meaning of this?
#number of sequences
seq_number = 100
#Re-defining dataset size for training
dataset_size = 8
max_iters = 40 #nb_epochs
#Defining sizes for input/target data
X_new=np.zeros((seq_number*dataset_size, timesteps, input_size_new, batch_size_new, 1))
#yhat=np.zeros((dataset_size, batch_mod, output))
Y_new=np.zeros((seq_number*dataset_size, output))
loss = 0
for m in range(0,dataset_size):
    if (m == 3-1 or  m == 4-1 or m == 15-1 or m == 16-1 or m == 18-1 ):
        if m == 3-1:
            initial_time = 700000
        if m == 4-1:
            initial_time = 300000
        if m == 15-1:
            initial_time = 400000
        if m == 16-1:
            initial_time = 200000
        if m == 18-1:
            initial_time = 400000
    else:
        initial_time = 0
    print('initial time:', initial_time)
    for i in range(0,seq_number):
        for j in range(0,timesteps):
            initial = initial_time+(i*batch_size_new*timesteps)+j*batch_size_new
            final = initial_time+(i*batch_size_new*timesteps)+((j+1)*batch_size_new)
            #print(initial_time+(i*batch_size_new*timesteps)+j*batch_size_new)
            #print(initial_time+(i*batch_size_new*timesteps)+((j+1)*batch_size_new))
            X_new[seq_number*m+i,j,:,0:batch_size_new,0] =  X[m,0,0,0:input_size_new,initial:final,0] 

#standardizing data
max_value = np.amax(abs(X_new))
min_value = np.amin(abs(X_new))
# print('MAX VALUE', max_value)
X_new = X_new/max_value # standardization by max value (all values between 0 and 1)
#size of data: (800, 10, 23, 100, 1)
Y_new[seq_number*2+33*2:seq_number*2+39*2,output-1] = 1
Y_new[seq_number*3+37*2:seq_number*3+42*2,output-1] = 1
Y_new[seq_number*14+21*2:seq_number*14+27*2,output-1] = 1
Y_new[seq_number*15+29*2:seq_number*15+37*2,output-1] = 1


print(X_new.shape, Y_new.shape)

SIZE sigbufs (23, 921600)
921600
(18, 1, 1, 23, 921600, 1)
(18, 10000, 1)
initial time: 0
initial time: 0
initial time: 700000
initial time: 300000
initial time: 0
initial time: 0
initial time: 0
initial time: 0
(800, 10, 23, 100, 1) (800, 1)


In [19]:


# sequences, timesteps, features, batches. (100 x nb_files, 10,23, 100,,1)
# define model
# initialize all parameters
sgd_batch_size = int(32)
layer_0 = Conv2D(2,2,2)
# add activation
layer_1 = MaxPool2D()
#layer_2 = GRU(dataset_size*seq_number,timesteps,1078,100) #sequences, timesteps, features, outputs
layer_2 = GRU(sgd_batch_size, timesteps, 1078, 100)
#layer_3 = Linear(100,1))
#Lin_bias_col = np.ones((800)) # create column of 1's for the bias.
#S_GRU_augmented = np.ones((sgd_batch_size,101))
# add activation
#training phase
dataset_size = 8
nb_ones =0
i = 0
order_SGD = np.arange(0, int(dataset_size*seq_number/sgd_batch_size))
print(order_SGD)
for i in range(Y_new.shape[0]):
    if Y_new[i]==1:
        nb_ones += 1
nb_zeros = 0
#forward pass
for n_iters in range(50):
    full_loss = 0
    #pick sequence randomly:
    #i = int(randint(200,300)/sgd_batch_size)
    np.random.shuffle(order_SGD)
    for p in range(int(dataset_size*seq_number/sgd_batch_size)):
        i = order_SGD[p]
        #print(i)
    #conv layer
        HConv = layer_0.forward(X_new[i*sgd_batch_size:(i+1)*sgd_batch_size,:,:,:,:]) # 5D data for train_data, 3D for Wconv 2D for Bconv
        #print(HConv.shape)
        YConv = reLU(HConv, deriv=False) # no requirement on shape
        DERIV_PROTECT = np.copy(YConv)
        DERIV_PROTECT = DERIV_PROTECT.flatten()
        DERIV_PROTECT[DERIV_PROTECT != 0.] = 1
        DERIV_PROTECT = DERIV_PROTECT.reshape(-1,10,22,99,2)
        #pooling layer
        pool_kernel = np.array([2,2])
        YPool, XArgmax = layer_1.forward(YConv,  pool_kernel) #5D data for YConv
        
        #flattening
        X_GRU_flat = YPool.reshape(YPool.shape[0],10,-1) # check size here should be 3D (100*nb_files, 10, 1078)
        
        #GRU
        yhat = layer_2.forward(X_GRU_flat)
        #last = S_GRU.shape[1]-1 # timesteps
        #S_GRU_augmented[:,1:101] =  S_GRU[:,last,:]
        #HLinear = layer_3.forward(S_GRU_augmented)
        #print(yhat)
        #calculate loss
        dy = np.zeros((yhat.shape))
        temp = np.zeros((yhat.shape[0]))
        rep_loss = np.zeros((yhat.shape[0]))
        Ytrue = Y_new[i*sgd_batch_size:(i+1)*sgd_batch_size].reshape(-1)
            
        temp[Ytrue==1] = 2*(yhat-Y_new[i*sgd_batch_size:(i+1)*sgd_batch_size]).reshape(-1)[Ytrue==1]
        temp[Ytrue==0] = 2*(yhat-Y_new[i*sgd_batch_size:(i+1)*sgd_batch_size]).reshape(-1)[Ytrue==0]
        dy=temp.reshape(-1,1)
        

        #********************************CLASS WEIGHTING************
        #for k in range(yhat.shape[0]):
         #   if Y_new[i*sgd_batch_size+k,:]==0:
          #      dhlin[k,:] = 2*(yhat[k,:] - Y_new[i*sgd_batch_size+k,:])
           # else:
            #    dhlin[k,:] = 20*(yhat[k,:] - Y_new[i*sgd_batch_size+k,:])
        #only 0.5/-0.5
        #dxlin, dwlin = layer_3.backward(dhlin, S_GRU_augmented)
        #dxlin = np.delete(dxlin, 0, 1)

        dsGRU, dxGRU = layer_2.backward(dy, X_GRU_flat)
        dyMaxPool = dxGRU.reshape(dxGRU.shape[0], dxGRU.shape[1],11,49,2)

        dxMaxPool = layer_1.backward(XArgmax, dyMaxPool)

        dxMaxPool_augmented = np.zeros((dxMaxPool.shape[0], dxMaxPool.shape[1], dxMaxPool.shape[2], dxMaxPool.shape[3]+1, dxMaxPool.shape[4]))
        dxMaxPool_augmented[:,:,:,0:dxMaxPool.shape[3],:]=dxMaxPool*DERIV_PROTECT[:,:,:,0:dxMaxPool.shape[3],:]
        dhConv2D = reLU(HConv, deriv=True)*dxMaxPool_augmented
        #print(dhConv2D.shape)
        layer_0.backward(dhConv2D, X_new[i*sgd_batch_size:(i+1)*sgd_batch_size,:,:,:,:])
    
        loss, __ = CrossEntropy(yhat, Y_new[i*sgd_batch_size:(i+1)*sgd_batch_size]) # works only for y = 0 or 1
        full_loss += loss
    #print(full_loss, dataset_size)
    #full_loss = full_loss/int(dataset_size/32)
    print("iter", n_iters, "---------", "loss =", full_loss)
    
    #wz, dwz,_,_,_,_,_,_,_,_,_,_ = layer_2.get_parameters()
    #print(wz[580:585,0:10], dwz[580:585,0:10])

Creating Conv2D layer
creating 2D Max pooling layer
creating GRU layer
(1078, 100)
(32, 10, 100)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
iter 0 --------- loss = 0.26452899889869724
iter 1 --------- loss = 0.16052445551142003
iter 2 --------- loss = 0.13627155696090995
iter 3 --------- loss = 0.13318537704804756
iter 4 --------- loss = 0.12406822375387183
iter 5 --------- loss = 0.10476236644192134
iter 6 --------- loss = 0.09787122677232576
iter 7 --------- loss = 0.08346428494484236
iter 8 --------- loss = 0.08234919487286066
iter 9 --------- loss = 0.06268271452083796
iter 10 --------- loss = 0.05105533928941032
iter 11 --------- loss = 0.05178323007580848
iter 12 --------- loss = 0.04729319395344658
iter 13 --------- loss = 0.046674752385038466
iter 14 --------- loss = 0.04278710035655143
iter 15 --------- loss = 0.0424824804750253
iter 16 --------- loss = 0.044656851359780425
iter 17 --------- loss = 0.040352072567666895
iter 18 --------- loss 

In [ ]:
def compute_error(yhat,y):
    err = 0
    yhat = np.round(yhat)
    diff = yhat-y
    for i in range(diff.shape[0]):
        if diff != 0:
            err+=1
    err = err/diff.shape[0]
    return err


In [27]:

#*******************************test phase***********************************************
startfile = 16
nb_files = 1
seq_number=100
#Defining sizes for input/target data
X_test=np.zeros((seq_number*nb_files, timesteps, input_size_new, batch_size_new, 1))

layer_2.change_input_size(seq_number*nb_files,10,100)
X_GRU_flat_augmented_test = np.ones((seq_number*nb_files,10,1079))
S_GRU_augmented_test = np.ones((seq_number*nb_files,101))

#for i in range(0,seq_number):
   # for j in range(0,timesteps):
    #    #print(initial, final, batch_size_new, file-1)
    #    initial = initial_time+(i*batch_size_new*timesteps)+j*batch_size_new
    #    final = initial_time+(i*batch_size_new*timesteps)+((j+1)*batch_size_new)
        #print(initial_time+(i*batch_size_new*timesteps)+j*batch_size_new)
        #print(initial_time+(i*batch_size_new*timesteps)+((j+1)*batch_size_new))
     #   X_test[i,j,:,0:batch_size_new,0] =  X[file-1,0,0,0:input_size_new,initial:final,0] 
for m in range(startfile,nb_files+startfile):
    if (m == 3-1 or  m == 4-1 or m == 15-1 or m == 16-1 or m == 18-1 ):
        if m == 3-1:
            initial_time = 700000
        if m == 4-1:
            initial_time = 300000
        if m == 15-1:
            initial_time = 400000
        if m == 16-1:
            initial_time = 200000
        if m == 18-1:
            initial_time = 400000
    else:
        initial_time = 800000
    print('initial time:', initial_time)
    for i in range(0,seq_number):
        for j in range(0,timesteps):
            initial = initial_time+(i*batch_size_new*timesteps)+j*batch_size_new
            final = initial_time+(i*batch_size_new*timesteps)+((j+1)*batch_size_new)
            #print(initial_time+(i*batch_size_new*timesteps)+j*batch_size_new)
            #print(initial_time+(i*batch_size_new*timesteps)+((j+1)*batch_size_new))
            X_test[seq_number*m+i-startfile*seq_number,j,:,0:batch_size_new,0] =  X[m,0,0,0:input_size_new,initial:final,0]    

   
max_value_2 = np.amax(abs(X_test))
min_value = np.amin(abs(X_test))
# print('MAX VALUE', max_value)
X_test = X_test/max_value_2

#generate predictions:
HConv = layer_0.forward(X_test) # 5D data for train_data, 3D for Wconv 2D for Bconv
YConv = reLU(HConv, deriv=False) # no requirement on shape
#pooling layer
pool_kernel = np.array([2,2])
YPool, XArgmax = layer_1.forward(YConv,  pool_kernel) #5D data for YConv
#flattening
X_GRU_flat = YPool.reshape(YPool.shape[0],10,-1) # check size here should be 3D (100*nb_files, 10, 1078)
#print(X_GRU_flat.shape)
#GRU
yhat_test = layer_2.forward(X_GRU_flat) # timesteps

file2 = open("CNN_GRU_testsetfile18_lowlevel_seed1", 'w')
np.savetxt(file2, yhat_test, delimiter="," )
file2.close()
#test_err = compute_error(yhat_test, Y_test)
#print(test_err)



initial time: 800000


In [23]:
np.round([1.5,1.4])

array([2., 1.])

In [ ]:
A = np.array([[1,2],[3,4]])
I = np.tile(A, (2,2,2))
print(I)

In [117]:
print(layer_0.W)
print(layer_0.B)


[[[-0.01349721 -0.79802286]
  [-0.01274448 -1.14339606]]

 [[ 0.00696058 -0.66652883]
  [ 0.01983425 -0.17549277]]]
[[-0.29894161 -1.45337415]]


In [33]:


fileY16 = open("Ytruth16.txt", 'w')
np.savetxt(fileY16, (Y_new[seq_number*15:seq_number*16,:]), delimiter=",", fmt='%.1f')
fileY16.close()

In [50]:
nb_ones =0
for i in range(Y_new.shape[0]):
    if Y_new[i]==1:
        nb_ones +=1
nb_ones/=1600
print(nb_ones, Y_new.shape)

0.03125 (1600, 1)


In [ ]:
def pow2_ternarization(W):
    nbits = 16
    nbfrac = 13
    nbint = nbits-nbfrac
    shape = W.shape
    W = W.flatten()
    Wclip = np.copy(W)
    Wclip[W <= -2**nbint]=-2**nbint
    Wclip[W >= 2**nbint]=2**nbint
    Wclip = Wclip.reshape(shape)
    Wclip = np.round(Wclip*2**nbfrac)*2**-nbfrac
    return Wclip
